services:
  ecommerce.basket.api:
    image: ${DOCKER_REGISTRY-}ecommercebasketapi
    build:
      context: .
      dockerfile: Services/Basket/ECommerce.Basket.API/Dockerfile

  ecommerce.catalog.api:
    image: ${DOCKER_REGISTRY-}ecommercecatalogapi
    build:
      context: .
      dockerfile: Services/Catalog/ECommerce.Catalog.API/Dockerfile

