apiVersion: apps/v1
kind: Deployment
metadata:
  name: urun-servisi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: urun-servisi
  template:
    metadata:
      labels:
        app: urun-servisi
    spec:
      containers:
      - name: urun-servisi
        image: eticaret/urun-servisi:1.0
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10